/* Generated By:JJTree: Do not edit this line. WithQueryCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import java.util.List;

import org.komodo.spi.query.sql.lang.WithQueryCommand;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.ElementSymbolImpl;
import org.teiid.query.sql.symbol.GroupSymbolImpl;

/**
 *
 */
public class WithQueryCommandImpl extends SimpleNode
    implements BaseSubqueryContainer<QueryCommandImpl>, WithQueryCommand<TCLanguageVisitorImpl, QueryCommandImpl> {

    private GroupSymbolImpl groupSymbol;

    private List<ElementSymbolImpl> columns;

    private QueryCommandImpl queryExpression;

    /**
     * @param p
     * @param id
     */
    public WithQueryCommandImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return group symbol
     */
    public GroupSymbolImpl getGroupSymbol() {
        return groupSymbol;
    }

    /**
     * @param groupSymbol the groupSymbol to set
     */
    public void setGroupSymbol(GroupSymbolImpl groupSymbol) {
        this.groupSymbol = groupSymbol;
    }

    /**
     * @return columns
     */
    public List<ElementSymbolImpl> getColumns() {
        return columns;
    }

    /**
     * @param columns
     */
    public void setColumns(List<ElementSymbolImpl> columns) {
        this.columns = columns;
    }

    /**
     * @return the queryExpression
     */
    public QueryCommandImpl getQueryExpression() {
        return this.queryExpression;
    }

    /**
     * @param queryExpression the queryExpression to set
     */
    public void setQueryExpression(QueryCommandImpl queryExpression) {
        this.queryExpression = queryExpression;
    }

    @Override
    public QueryCommandImpl getCommand() {
        return getQueryExpression();
    }

    @Override
    public void setCommand(QueryCommandImpl command) {
        setQueryExpression(command);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.columns == null) ? 0 : this.columns.hashCode());
        result = prime * result + ((this.groupSymbol == null) ? 0 : this.groupSymbol.hashCode());
        result = prime * result + ((this.queryExpression == null) ? 0 : this.queryExpression.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        WithQueryCommandImpl other = (WithQueryCommandImpl)obj;
        if (this.columns == null) {
            if (other.columns != null) return false;
        } else if (!this.columns.equals(other.columns)) return false;
        if (this.groupSymbol == null) {
            if (other.groupSymbol != null) return false;
        } else if (!this.groupSymbol.equals(other.groupSymbol)) return false;
        if (this.queryExpression == null) {
            if (other.queryExpression != null) return false;
        } else if (!this.queryExpression.equals(other.queryExpression)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public WithQueryCommandImpl clone() {
        WithQueryCommandImpl clone = new WithQueryCommandImpl(this.parser, this.id);

        if(getColumns() != null)
            clone.setColumns(cloneList(getColumns()));
        if(getGroupSymbol() != null)
            clone.setGroupSymbol(getGroupSymbol().clone());
        if(getQueryExpression() != null)
            clone.setQueryExpression(getQueryExpression().clone());

        return clone;
    }

}
/* JavaCC - OriginalChecksum=78388b507c1605f75762901f62007b34 (do not edit this line) */
