/* Generated By:JJTree: Do not edit this line. Alter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang.v8;

import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.v8.Teiid8ClientParser;
import org.teiid.query.sql.lang.AlterProcedureImpl;
import org.teiid.query.sql.proc.CreateProcedureCommandImpl;

/**
 * From Teiid version 8 onwards the AlterProcedure has a CreateProcedureCommand generic
 */
public class Alter8ProcedureImpl extends AlterProcedureImpl<CreateProcedureCommandImpl> {

    /**
     * @param p
     * @param id
     */
    public Alter8ProcedureImpl(Teiid8ClientParser p, int id) {
        super(p, id);
    }

    @Override
    public int getType() {
        return TYPE_ALTER_PROC;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public Alter8ProcedureImpl clone() {
        Alter8ProcedureImpl clone = new Alter8ProcedureImpl((Teiid8ClientParser) this.parser, this.id);

        if(getDefinition() != null)
            clone.setDefinition(getDefinition().clone());
        if(getTarget() != null)
            clone.setTarget(getTarget().clone());
        if(getSourceHint() != null)
            clone.setSourceHint(getSourceHint());
        if(getOption() != null)
            clone.setOption(getOption().clone());

        copyMetadataState(clone);

        return clone;
    }

}
/* JavaCC - OriginalChecksum=4c2a7e700d4af2b1569d4947a1d82223 (do not edit this line) */
