//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 10:48:40 AM BST 
//


package org.komodo.teiid.client.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import com.fasterxml.jackson.annotation.*;
import javax.xml.bind.annotation.XmlType;


/**
 * Translator Property
 * 
 * <p>Java class for translatorProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="translatorProperty"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;&gt;property"&gt;
 *       &lt;attribute name="suggestedValue" type="{}translatorPropertyEnumType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "translatorProperty")
public class TranslatorProperty
    extends Property
{

    @XmlAttribute(name = "suggestedValue")
    protected TranslatorPropertyEnumType suggestedValue;

    /**
     * Gets the value of the suggestedValue property.
     * 
     * @return
     *     possible object is
     *     {@link TranslatorPropertyEnumType }
     *     
     */
    public TranslatorPropertyEnumType getSuggestedValue() {
        return suggestedValue;
    }

    /**
     * Sets the value of the suggestedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslatorPropertyEnumType }
     *     
     */
    public void setSuggestedValue(TranslatorPropertyEnumType value) {
        this.suggestedValue = value;
    }

}
