//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 10:48:40 AM BST 
//


package org.komodo.teiid.client.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vdbPropertyEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vdbPropertyEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="pounds"/&gt;
 *     &lt;enumeration value="euros"/&gt;
 *     &lt;enumeration value="dollars"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "vdbPropertyEnumType")
@XmlEnum
public enum VdbPropertyEnumType {

    @XmlEnumValue("pounds")
    POUNDS("pounds"),
    @XmlEnumValue("euros")
    EUROS("euros"),
    @XmlEnumValue("dollars")
    DOLLARS("dollars");
    private final String value;

    VdbPropertyEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VdbPropertyEnumType fromValue(String v) {
        for (VdbPropertyEnumType c: VdbPropertyEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
