/* Generated By:JJTree: Do not edit this line. Alter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import org.komodo.spi.query.sql.lang.AlterProcedure;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.BaseExpression;


/**
 *
 * @param <T>
 */
public abstract class AlterProcedureImpl<T extends CommandImpl> extends AlterImpl<T> implements AlterProcedure<BaseExpression, TCLanguageVisitorImpl> {

    /**
     * @param p
     * @param id
     */
    public AlterProcedureImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    @Override
    public abstract AlterProcedureImpl clone();
}
/* JavaCC - OriginalChecksum=4c2a7e700d4af2b1569d4947a1d82223 (do not edit this line) */
