/* Generated By:JJTree: Do not edit this line. ExpressionCriteria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import org.komodo.spi.query.sql.lang.ExpressionCriteria;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.BaseExpression;

/**
 *
 */
public class ExpressionCriteriaImpl extends CriteriaImpl implements ExpressionCriteria<TCLanguageVisitorImpl> {

    private BaseExpression expression;

    /**
     * @param p
     * @param id
     */
    public ExpressionCriteriaImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return the expression
     */
    public BaseExpression getExpression() {
        return expression;
    }

    /**
     * @param expression the expression to set
     */
    public void setExpression(BaseExpression expression) {
        this.expression = expression;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.expression == null) ? 0 : this.expression.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        ExpressionCriteriaImpl other = (ExpressionCriteriaImpl)obj;
        if (this.expression == null) {
            if (other.expression != null) return false;
        } else if (!this.expression.equals(other.expression)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public ExpressionCriteriaImpl clone() {
        ExpressionCriteriaImpl clone = new ExpressionCriteriaImpl(this.parser, this.id);

        if(getExpression() != null)
            clone.setExpression(getExpression().clone());

        return clone;
    }

}
/* JavaCC - OriginalChecksum=ac75024b68d2274a23c0fca3d91ba8f4 (do not edit this line) */
