/* Generated By:JJTree: Do not edit this line. Into.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import org.komodo.spi.query.sql.lang.Into;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.GroupSymbolImpl;

/**
 *
 */
public class IntoImpl extends SimpleNode implements Into<TCLanguageVisitorImpl> {

    private GroupSymbolImpl group;

    /**
     * @param p
     * @param id
     */
    public IntoImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * Get group held by clause
     * @return Group held by clause
     */
    @Override
    public GroupSymbolImpl getGroup() {
        return this.group;
    }

    /**
     * Set the group held by the clause
     * @param group Group to hold
     */
    public void setGroup(GroupSymbolImpl group) {
        this.group = group;
    } 

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.group == null) ? 0 : this.group.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        IntoImpl other = (IntoImpl)obj;
        if (this.group == null) {
            if (other.group != null) return false;
        } else if (!this.group.equals(other.group)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public IntoImpl clone() {
        IntoImpl clone = new IntoImpl(this.parser, this.id);

        if(getGroup() != null)
            clone.setGroup(getGroup().clone());

        return clone;
    }

}
/* JavaCC - OriginalChecksum=c043560b07b761462fb1c893f608a51c (do not edit this line) */
