/* Generated By:JJTree: Do not edit this line. JoinType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import org.komodo.spi.query.JoinTypeTypes;
import org.komodo.spi.query.sql.lang.JoinType;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;

/**
 *
 */
public class JoinTypeImpl extends SimpleNode implements JoinType<TCLanguageVisitorImpl>{

    private JoinTypeTypes kind = JoinTypeTypes.JOIN_CROSS;

    /**
     * @param p
     * @param id
     */
    public JoinTypeImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return the kind
     */
    public JoinTypeTypes getKind() {
        return kind;
    }

    /**
     * @param kind the kind to set
     */
    public void setKind(JoinTypeTypes kind) {
        this.kind = kind;
    }

    /**
     * Used only for comparison during equals, not by users of this class
     * @return Type code for object
     */
    @Override
    public int getTypeCode() { 
        return kind.getTypeCode();
    }

    /**
     * Check if this join type is an outer join.
     * @return True if left/right/full outer, false if inner/cross
     */
    @Override
    public boolean isOuter() { 
        return kind.isOuter();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.kind == null) ? 0 : this.kind.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        JoinTypeImpl other = (JoinTypeImpl)obj;
        if (this.kind != other.kind) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public JoinTypeImpl clone() {
        JoinTypeImpl clone = new JoinTypeImpl(this.parser, this.id);

        if(getKind() != null)
            clone.setKind(getKind());

        return clone;
    }

}
/* JavaCC - OriginalChecksum=682a038ace51527d7a11065b4087303a (do not edit this line) */
