/* Generated By:JJTree: Do not edit this line. SetCriteria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import java.util.Collection;

import org.komodo.spi.query.sql.lang.SetCriteria;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.BaseExpression;

/**
 *
 */
public class SetCriteriaImpl extends AbstractSetCriteria implements SetCriteria<BaseExpression, TCLanguageVisitorImpl> {

    /** The set of value expressions */
    private Collection<BaseExpression> values;

    private boolean allConstants;

    /**
     * @param p
     * @param id
     */
    public SetCriteriaImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return the values
     */
    @Override
    public Collection<BaseExpression> getValues() {
        return this.values;
    }

    /**
     * @param values the values to set
     */
    @Override
    public void setValues(Collection<BaseExpression> values) {
        this.values = values;
    }

    /**
     * @return allConstants
     */
    public boolean isAllConstants() {
        return allConstants;
    }
    
    /**
     * @param allConstants
     */
    public void setAllConstants(boolean allConstants) {
        this.allConstants = allConstants;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + (this.allConstants ? 1231 : 1237);
        result = prime * result + ((this.values == null) ? 0 : this.values.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        SetCriteriaImpl other = (SetCriteriaImpl)obj;
        if (this.allConstants != other.allConstants)
            return false;
        if (this.values == null) {
            if (other.values != null)
                return false;
        } else if (this.values.size() != other.values.size() || 
            (! this.values.containsAll(other.values)))
            return false;

        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public SetCriteriaImpl clone() {
        SetCriteriaImpl clone = new SetCriteriaImpl(this.parser, this.id);

        if(getValues() != null)
            clone.setValues(cloneCollection(getValues()));
        if(getExpression() != null)
            clone.setExpression(getExpression().clone());
        clone.setNegated(isNegated());

        clone.allConstants = allConstants;

        return clone;
    }

}
/* JavaCC - OriginalChecksum=9f7eb5b2819c59fc94d4b273872b85f1 (do not edit this line) */
