/* Generated By:JJTree: Do not edit this line. SetClauseList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import org.komodo.spi.query.sql.lang.SetClauseList;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.symbol.ElementSymbolImpl;
import org.teiid.query.sql.symbol.BaseExpression;

/**
 *
 */
public class SetClauseListImpl extends SimpleNode implements SetClauseList<TCLanguageVisitorImpl> {

    private List<SetClauseImpl> setClauses = new ArrayList<SetClauseImpl>();

    /**
     * @param p
     * @param id
     */
    public SetClauseListImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return a non-updateable map representation
     */
    public LinkedHashMap<ElementSymbolImpl, BaseExpression> getClauseMap() {
        LinkedHashMap<ElementSymbolImpl, BaseExpression> result = new LinkedHashMap<ElementSymbolImpl, BaseExpression>();
        for (SetClauseImpl clause : this.setClauses) {
            result.put(clause.getSymbol(), clause.getValue());
        }
        return result;
    }

    /**
     * @return set clauses
     */
    public List<SetClauseImpl> getClauses() {
        return this.setClauses;
    }

    /**
     * @return clauses is empty
     */
    public boolean isEmpty() {
        return this.setClauses.isEmpty();
    }

    /**
     * @param clause
     */
    public void addClause(SetClauseImpl clause) {
        this.setClauses.add(clause);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.setClauses == null) ? 0 : this.setClauses.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        SetClauseListImpl other = (SetClauseListImpl)obj;
        if (this.setClauses == null) {
            if (other.setClauses != null) return false;
        } else if (!this.setClauses.equals(other.setClauses)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public SetClauseListImpl clone() {
        SetClauseListImpl clone = new SetClauseListImpl(this.parser, this.id);
        clone.getClauses().addAll(cloneList(getClauses()));
        return clone;
    }

}
/* JavaCC - OriginalChecksum=03e0d8ce7120831af6c8c5e5b956b453 (do not edit this line) */
