/* Generated By:JJTree: Do not edit this line. SetQuery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.lang;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.komodo.spi.query.metadata.QueryMetadataInterface;
import org.komodo.spi.query.sql.lang.SetQuery;
import org.teiid.core.types.DefaultDataTypeManager;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidNodeFactory.ASTNodes;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.resolver.util.ResolverUtil;
import org.teiid.query.sql.symbol.AliasSymbolImpl;
import org.teiid.query.sql.symbol.BaseExpression;
import org.teiid.query.sql.symbol.SymbolImpl;
import org.teiid.query.sql.util.SymbolMap;

/**
 *
 */
public class SetQueryImpl extends QueryCommandImpl
    implements SetQuery<QueryCommandImpl, OrderByImpl, QueryImpl, BaseExpression, TCLanguageVisitorImpl>{

    private boolean all = true;

    private Operation operation;                     

    private QueryCommandImpl leftQuery;

    private QueryCommandImpl rightQuery;

    private List<Class<?>> projectedTypes = null;  //set during resolving

    private QueryMetadataInterface metadata = null; // set during resolving

    /**
     * @param p
     * @param id
     */
    public SetQueryImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * Return type of command.
     * @return TYPE_QUERY
     */
    @Override
    public int getType() {
        return TYPE_QUERY;
    }
    
    /**
     * Set type of operation
     * @param operation Operation constant as defined in this class
     */
    public void setOperation(Operation operation) { 
        this.operation = operation;
    }
    
    /**
     * Get operation for this set
     * @return Operation as defined in this class
     */
    @Override
    public Operation getOperation() { 
        return this.operation;
    }

    /**
     * @return all
     */
    @Override
    public boolean isAll() {
        return this.all;
    }

    /**
     * @param all
     */
    @Override
    public void setAll(boolean all) {
        this.all = all;
    }

    /**
     * @return left query
     */
    @Override
    public QueryCommandImpl getLeftQuery() {
        return this.leftQuery;
    }

    /**
     * @param leftQuery
     */
    @Override
    public void setLeftQuery(QueryCommandImpl leftQuery) {
        this.leftQuery = leftQuery;
    }
    
    /**
     * @return right query
     */
    @Override
    public QueryCommandImpl getRightQuery() {
        return this.rightQuery;
    }
    
    /**
     * @param rightQuery
     */
    @Override
    public void setRightQuery(QueryCommandImpl rightQuery) {
        this.rightQuery = rightQuery;
    }

    /**
     * @return the left and right queries as a list.  This list cannot be modified.
     */
    @Override
    public List<QueryCommandImpl> getQueryCommands() {
        return Collections.unmodifiableList(Arrays.asList(leftQuery, rightQuery));
    }

    /**
     * @return projected query
     */
    @Override
    public QueryImpl getProjectedQuery() {
        if (leftQuery instanceof SetQueryImpl) {
            return ((SetQueryImpl)leftQuery).getProjectedQuery();
        }
        return (QueryImpl)leftQuery;
    }

    /**
     * Get the ordered list of all elements returned by this query.  These elements
     * may be ElementSymbols or ExpressionSymbols but in all cases each represents a 
     * single column.
     * @return Ordered list of SingleElementSymbol
     */
    @Override
    public List<BaseExpression> getProjectedSymbols() {
        QueryImpl query = getProjectedQuery();
        List projectedSymbols = query.getProjectedSymbols();
        if (projectedTypes != null) {
            return getTypedProjectedSymbols(projectedSymbols, projectedTypes, metadata);
        } 
        return projectedSymbols;
    }

    /**
     * @param projectedTypes The projectedSymbols to set.
     * @param metadata
     */
    public void setProjectedTypes(List<Class<?>> projectedTypes, QueryMetadataInterface metadata) {
        this.projectedTypes = projectedTypes;
        this.metadata = metadata;
    }

    /** 
     * @return Returns the projectedTypes.
     */
    public List<Class<?>>  getProjectedTypes() {
        return this.projectedTypes;
    }

    public static List<BaseExpression> getTypedProjectedSymbols(List<? extends BaseExpression> acutal, List<Class<?>> projectedTypes, QueryMetadataInterface metadata) {
        List<BaseExpression> newProject = new ArrayList<BaseExpression>();
        for (int i = 0; i < acutal.size(); i++) {
            BaseExpression originalSymbol = acutal.get(i);
            BaseExpression symbol = originalSymbol;
            Class<?> type = projectedTypes.get(i);
            if (symbol.getType() != type) {
                symbol = SymbolMap.getExpression(originalSymbol);
                try {
                    symbol = ResolverUtil.convertExpression(symbol, DefaultDataTypeManager.getInstance(symbol.getTeiidVersion()).getDataTypeName(type), metadata);
                } catch (Exception err) {
                     throw new RuntimeException(err);
                }

                if (originalSymbol instanceof SymbolImpl) {
                    TeiidClientParser teiidParser = originalSymbol.getTeiidParser();
                    AliasSymbolImpl aliasSymbol = teiidParser.createASTNode(ASTNodes.ALIAS_SYMBOL);
                    aliasSymbol.setName(SymbolImpl.getShortName(originalSymbol));
                    aliasSymbol.setSymbol(symbol);
                    symbol = aliasSymbol;
                } 
            }
            newProject.add(symbol);
        }
        return newProject;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + (this.all ? 1231 : 1237);
        result = prime * result + ((this.leftQuery == null) ? 0 : this.leftQuery.hashCode());
        result = prime * result + ((this.operation == null) ? 0 : this.operation.hashCode());
        result = prime * result + ((this.rightQuery == null) ? 0 : this.rightQuery.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        SetQueryImpl other = (SetQueryImpl)obj;
        if (this.all != other.all) return false;
        if (this.leftQuery == null) {
            if (other.leftQuery != null) return false;
        } else if (!this.leftQuery.equals(other.leftQuery)) return false;
        if (this.operation != other.operation) return false;
        if (this.rightQuery == null) {
            if (other.rightQuery != null) return false;
        } else if (!this.rightQuery.equals(other.rightQuery)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public SetQueryImpl clone() {
        SetQueryImpl clone = new SetQueryImpl(this.parser, this.id);

        this.copyMetadataState(clone);

        if(getOperation() != null)
            clone.setOperation(getOperation());
        clone.setAll(isAll());
        if(getLeftQuery() != null)
            clone.setLeftQuery(getLeftQuery().clone());
        if(getRightQuery() != null)
            clone.setRightQuery(getRightQuery().clone());
        if(getOrderBy() != null)
            clone.setOrderBy(getOrderBy().clone());
        if(getLimit() != null)
            clone.setLimit(getLimit().clone());
        if(getWith() != null)
            clone.setWith(cloneList(getWith()));
        if(getSourceHint() != null)
            clone.setSourceHint(getSourceHint());
        if(getOption() != null)
            clone.setOption(getOption().clone());
        if (getProjectedTypes() != null) {
            clone.setProjectedTypes(new ArrayList<Class<?>>(getProjectedTypes()), this.metadata);
        }

        return clone;
    }

}
/* JavaCC - OriginalChecksum=15a0b6183a79ec40affab72ee83028a6 (do not edit this line) */
