#%RAML 0.8
---
title: vdb-builder API
version: v1
baseUri: http://localhost:8080/vdb-builder/api/{version}
mediaType: application/json

/vdbs:
    get:
        description: List available vdbs
        responses:
            200:
                body:
                    application/json:
                        example: !include json/vdbs.json
    put:
    post:
    /{vdbId}:
        put:
        delete:
            responses:
                200:
                404:
                    body:
                        application/json:
                            example: "No vdb named portfolio"
/vdb:
    /{vdbId}:
        get:
            description: Retrieve the content for the given vdb
            headers:
                Accept:
                    enum: [application/json, application/xml]
                    required: true
            responses:
                200:
                    body:
                        application/json:
                            example: !include json/vdbsContent.json
                        application/xml:
                            example: !include xml/vdbsContent.xml
                404:
                    body:
                        application/json:
                            example: "No vdb named portfolio"
                        application/xml:
                            example: "No vdb content for vdb named portfolio"
                406:
                    description: Request has invalid Accept header
        post: