/* Generated By:JJTree: Do not edit this line. CreateUpdateProcedureCommand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.proc;

import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.komodo.spi.annotation.Removed;
import org.komodo.spi.query.sql.proc.CreateProcedureCommand;
import org.komodo.spi.runtime.version.DefaultTeiidVersion.Version;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.lang.CommandImpl;
import org.teiid.query.sql.lang.StoredProcedureImpl;
import org.teiid.query.sql.symbol.ElementSymbolImpl;
import org.teiid.query.sql.symbol.BaseExpression;
import org.teiid.query.sql.symbol.GroupSymbolImpl;

/**
 *
 */
@Removed(Version.TEIID_8_0)
public class CreateUpdateProcedureCommandImpl extends CommandImpl
    implements CreateProcedureCommand<BlockImpl, GroupSymbolImpl, BaseExpression, TCLanguageVisitorImpl> {

    // top level block for the procedure
    private BlockImpl block;

    //whether it is update procedure or virtual stored procedure, default to update procedure
    private boolean isUpdateProcedure = true;

    private List<? extends BaseExpression> projectedSymbols;

    //command that returns resultset. For virtual procedure only.
    private CommandImpl resultsCommand;

    // the command the user submitted against the virtual group being updated
    private CommandImpl userCommand;

    private GroupSymbolImpl virtualGroup;

    // map between elements on the virtual groups and the elements in the
    // transformation query that define it.
    private Map<ElementSymbolImpl, BaseExpression> symbolMap;

    /**
     * @param p
     * @param id
     */
    public CreateUpdateProcedureCommandImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * Return type of command to make it easier to build switch statements by command type.
     * @return The type of this command
     */
    @Override
    public int getType() {
        return TYPE_UPDATE_PROCEDURE;   
    }

    /**
     * @return the block
     */
    @Override
    public BlockImpl getBlock() {
        return block;
    }

    /**
     * @param block the block to set
     */
    @Override
    public void setBlock(BlockImpl block) {
        this.block = block;
    }

    /**
     * @return the isUpdateProcedure
     */
    public boolean isUpdateProcedure() {
        return this.isUpdateProcedure;
    }

    /**
     * @param isUpdateProcedure the isUpdateProcedure to set
     */
    public void setUpdateProcedure(boolean isUpdateProcedure) {
        this.isUpdateProcedure = isUpdateProcedure;
    }

    /**
     * Get the ordered list of all elements returned by this query.  These elements
     * may be ElementSymbols or ExpressionSymbols but in all cases each represents a 
     * single column.
     * @return Ordered list of SingleElementSymbol
     */
    @Override
    public List getProjectedSymbols(){
        if(this.projectedSymbols != null){
            return this.projectedSymbols;
        }
        if(!isUpdateProcedure){
            if(this.resultsCommand == null){
                //user may have not entered any query yet
                return Collections.EMPTY_LIST;
            }
            List<? extends BaseExpression> symbols = this.resultsCommand.getProjectedSymbols();
            if (this.resultsCommand instanceof StoredProcedureImpl) {
                StoredProcedureImpl sp = (StoredProcedureImpl)this.resultsCommand;
                if (sp.isCallableStatement()) {
                    symbols = sp.getResultSetColumns();
                }
            }
            setProjectedSymbols(symbols);
            return this.projectedSymbols;
        }
        this.projectedSymbols = getUpdateCommandSymbol();
        return this.projectedSymbols;        
    }

    /**
     * @param projSymbols
     */
    public void setProjectedSymbols(List<? extends BaseExpression> projSymbols) {
        projectedSymbols = projSymbols;
    }

    /**
     * @return Command
     */
    public CommandImpl getResultsCommand() {
        return resultsCommand;
    }

    /**
     * @param command
     */
    public void setResultsCommand(CommandImpl command) {
        resultsCommand = command;
    }

    /**
     * Get the user's command to which this obj which is the subcommand
     * @return The user's command
     */ 
    public CommandImpl getUserCommand() {
        return this.userCommand;    
    }

    /**
     * Set the user's command to which this obj which is the subcommand
     * @param command The user's command
     */
    public void setUserCommand(CommandImpl command) {
        this.userCommand = command;
    }

    /**
     * @return virtual group
     */
    public GroupSymbolImpl getVirtualGroup() {
        return this.virtualGroup;
    }

    /**
     * @param virtualGroup
     */
    @Override
    public void setVirtualGroup(GroupSymbolImpl virtualGroup) {
        this.virtualGroup = virtualGroup;
    }

    /**
     * Set the symbol map between elements on the virtual group being updated and the
     * elements on the transformation query.
     * @param symbolMap Map of virtual group elements -> elements that define those
     */
    public void setSymbolMap(Map<ElementSymbolImpl, BaseExpression> symbolMap) {
        this.symbolMap = symbolMap;
    }

    /**
     * Get the symbol map between elements on the virtual group being updated and the
     * elements on the transformation query.
     * @return Map of virtual group elements -> elements that define those
     */
    public Map<ElementSymbolImpl, BaseExpression> getSymbolMap() {
        return this.symbolMap;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + (this.isUpdateProcedure ? 1231 : 1237);
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        CreateUpdateProcedureCommandImpl other = (CreateUpdateProcedureCommandImpl)obj;
        if (this.isUpdateProcedure != other.isUpdateProcedure) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public CreateUpdateProcedureCommandImpl clone() {
        CreateUpdateProcedureCommandImpl clone = new CreateUpdateProcedureCommandImpl(this.parser, this.id);

        clone.setUpdateProcedure(isUpdateProcedure());
        if(getBlock() != null)
            clone.setBlock(getBlock().clone());
        if(getSourceHint() != null)
            clone.setSourceHint(getSourceHint());
        if(getOption() != null)
            clone.setOption(getOption().clone());
        if (this.virtualGroup != null)
            clone.virtualGroup = this.virtualGroup.clone();

        this.copyMetadataState(clone);
        return clone;
    }

}
/* JavaCC - OriginalChecksum=f346ab2e5ff020b1b349d6d7fdcc5974 (do not edit this line) */
