/* Generated By:JJTree: Do not edit this line. WindowSpecification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=TeiidNodeFactory,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.symbol;

import java.util.List;

import org.komodo.spi.query.sql.symbol.WindowSpecification;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.lang.OrderByImpl;
import org.teiid.query.sql.lang.SimpleNode;

/**
 *
 */
public class WindowSpecificationImpl extends SimpleNode implements WindowSpecification<TCLanguageVisitorImpl> {

    private List<BaseExpression> partition;

    private OrderByImpl orderBy;

    /**
     * @param p
     * @param id
     */
    public WindowSpecificationImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return the partition
     */
    public List<BaseExpression> getPartition() {
        return this.partition;
    }

    /**
     * @param partition the partition to set
     */
    public void setPartition(List<BaseExpression> partition) {
        this.partition = partition;
    }

    /**
     * @return the orderBy
     */
    public OrderByImpl getOrderBy() {
        return this.orderBy;
    }

    /**
     * @param orderBy the orderBy to set
     */
    public void setOrderBy(OrderByImpl orderBy) {
        this.orderBy = orderBy;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.orderBy == null) ? 0 : this.orderBy.hashCode());
        result = prime * result + ((this.partition == null) ? 0 : this.partition.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        WindowSpecificationImpl other = (WindowSpecificationImpl)obj;
        if (this.orderBy == null) {
            if (other.orderBy != null) return false;
        } else if (!this.orderBy.equals(other.orderBy)) return false;
        if (this.partition == null) {
            if (other.partition != null) return false;
        } else if (!this.partition.equals(other.partition)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public WindowSpecificationImpl clone() {
        WindowSpecificationImpl clone = new WindowSpecificationImpl(this.parser, this.id);

        if(getOrderBy() != null)
            clone.setOrderBy(getOrderBy().clone());
        if(getPartition() != null)
            clone.setPartition(cloneList(getPartition()));

        return clone;
    }

}
/* JavaCC - OriginalChecksum=955691556e321ccc1bc9cfb1cbe30f7c (do not edit this line) */
