/* Generated By:JJTree: Do not edit this line. XMLAttributes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.teiid.query.sql.symbol;

import java.util.List;

import org.komodo.spi.query.sql.symbol.XMLAttributes;
import org.teiid.query.parser.TCLanguageVisitorImpl;
import org.teiid.query.parser.TeiidClientParser;
import org.teiid.query.sql.lang.SimpleNode;

/**
 *
 */
public class XMLAttributesImpl extends SimpleNode implements XMLAttributes<TCLanguageVisitorImpl> {

    private List<DerivedColumnImpl> args;

    /**
     * @param p
     * @param id
     */
    public XMLAttributesImpl(TeiidClientParser p, int id) {
        super(p, id);
    }

    /**
     * @return the args
     */
    public List<DerivedColumnImpl> getArgs() {
        return this.args;
    }

    /**
     * @param args the args to set
     */
    public void setArgs(List<DerivedColumnImpl> args) {
        this.args = args;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((this.args == null) ? 0 : this.args.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!super.equals(obj)) return false;
        if (getClass() != obj.getClass()) return false;
        XMLAttributesImpl other = (XMLAttributesImpl)obj;
        if (this.args == null) {
            if (other.args != null) return false;
        } else if (!this.args.equals(other.args)) return false;
        return true;
    }

    /** Accept the visitor. **/
    @Override
    public void acceptVisitor(TCLanguageVisitorImpl visitor) {
        visitor.visit(this);
    }

    @Override
    public XMLAttributesImpl clone() {
        XMLAttributesImpl clone = new XMLAttributesImpl(this.parser, this.id);

        if(getArgs() != null)
            clone.setArgs(cloneList(getArgs()));

        return clone;
    }

}
/* JavaCC - OriginalChecksum=b3038eb7357f2bdba91bc701ecebddd9 (do not edit this line) */
